### ISSUE TITLE
Execution failed for task ':flutter_tappay:bundleReleaseAar'

### ISSUE THREAD

**Issue by oscar790512** [Tokenyet/Flutter_Tappay#1]
When I build apk or run in flutter, I got these message:
---------------------------------------------------------------------------------
* What went wrong:                                                      
Execution failed for task ':flutter_tappay:bundleReleaseAar'.           
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :flutter_tappay project caused this error: /Users/xxx/app/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tappay-0.3.0+2/android/libs/tpdirect.aar
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 22s
---------------------------------------------------------------------------------
How can I resolve this error? thx. There's my flutter doctor:
---------------------------------------------------------------------------------

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale zh-Hant-TW)
    • Flutter version 1.17.5 at /Users/oscar790512/app/flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/oscar790512/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
---------------------------------------------------------------------------------

**Comment by Tokenyet** [comment]
Here are some questions:
1. Which IDE did you use?
2. How did you come with this issue? ex. `flutter run` , `flutter run --release` or something else?
3. Have you tried to download this project, then run the example to see If It's working on your machine?

**Comment by oscar790512** [comment]
Thanks for answer me, here're the answers for the questions:
1. IntelliJ IDEA, 2019.3.5.
2. All about flutter run, flutter build apk, flutter build apk --release in Android.
3. I haven't download this project to run in my machine. But I use dependencies with pubspec.yaml in my project, and I can run with simulator in IOS, but the error appear when I run in Android simulator and build apk.

**Comment by oscar790512** [comment]
I have download your project to test, there're no error in your project;
So I think that could be some setting in my project is different to your project.

**Comment by Tokenyet** [comment]
I tried for new flutter version, there is no error on my side. Did you follow the preparation part for Android?

Here are my steps to check the project:

1. `flutter create new_project`
2. add ` flutter_tappay: ^0.3.0+2` in *pubspec.yaml*
3. follow the preparation
4. `flutter run`, It's still working in 1.17.5 for me 😕 

Hope you find what's the difference in your setting, and share your feedback 😓

**Comment by oscar790512** [comment]
Hi,
I tried to changed my android build gradle version, than the error be resolved.
My version was 4.0.0., When I changed to 3.5.0 than my project success to build apk.
thanks for your help~, there's the detail:

android/build.gradle

buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'  //when I use 4.0.0 will get error
        classpath 'com.google.gms:google-services:4.3.0'
    }

}

**Comment by Tokenyet** [comment]
Thanks for the feedback!
